name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Playit.gg
        run: |
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/playit.gpg
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit.list
          sudo apt update
          sudo apt install playit -y

      - name: Emergency start.sh creation
        run: |
          # Если файла нет, создаем его на лету
          if [ ! -f start.sh ]; then
            echo "#!/bin/bash" > start.sh
            echo "java -Xms2G -Xmx2G -jar paper.jar nogui" >> start.sh
            chmod +x start.sh
            echo "Файл start.sh был создан автоматически."
          fi

      - name: Run Server
        run: |
          chmod +x start.sh
          # Запуск туннеля. Если секрет пустой, он напишет ошибку в лог.
          playit --secret "${{ secrets.PLAYIT_TOKEN }}" &
          ./start.sh
